version: "3"

services:
    sandbox_mysql:
        build:
            context: .
            dockerfile: docker/Dockerfile.mysql
        image: sandbox_mysql 
        command: mysqld --character-set-server=utf8mb4 --character-set-filesystem=utf8mb4
        ports:
          - "13306:3306"
        volumes:
          - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
          - sandbox_mysql:/var/lib/mysql
        environment:
          MYSQL_DATABASE: sandbox 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: sandbox 
          MYSQL_PASSWORD: sandbox 
        networks:
          - sandbox 

volumes:
    sandbox_mysql:
networks:
    sandbox:
